http:
  port: 8080
admin:
  port: 9876
apiEndpoints:
  api:
    paths:
      - /ip
  actors:
    paths:
      - '/actors'
      - '/actors/*'
  movies:
    paths:
      - '/movies'
      - '/movies/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  actorService:
    url: 'http://api-actor:3000'
  movieService:
    url: 'http://412143bfb37a.ngrok.io'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  actorPipeline:
    apiEndpoints:
      - actors
    policies:
      - proxy:
          - action:
              serviceEndpoint: actorService
              changeOrigin: true
  moviePipeline:
    apiEndpoints:
      - movies
    policies:
      - proxy:
          - action:
              serviceEndpoint: movieService
              changeOrigin: true
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
