version: "3.8"

networks:
  # graphql:
  # rest:
  # combi:
  # author-net:
  # book-net:
  all:

services:
  #### GraphQL ####
  graphql-gateway:
    build: ./GraphQl/gateway
    container_name: graphql-gateway
    ports:
      - "8081:8080"
      - "4000:4000"
    environment:
      - LOG_LEVEL=debug
    networks:
      - all
    depends_on:
      - graphql-api-author
      - graphql-api-book

  graphql-api-author:
    build: ./GraphQl/services/author
    container_name: graphql-api-author
    command: "node index.js"
    ports:
      - "4001:4001"
    environment:
      - LOG_LEVEL=debug
    networks:
      - all

  graphql-api-book:
    build: ./GraphQl/services/book
    container_name: graphql-api-book
    command: "node index.js"
    ports:
      - "4002:4002"
    environment:
      - LOG_LEVEL=debug
    networks:
      - all

  #### REST ####
  rest-gateway:
    build: ./REST/gateway
    container_name: rest-gateway
    ports:
      - "8080:8080"
      - "9876:9876"
      - "8443:8443"
    environment:
      - LOG_LEVEL=debug
    networks:
      - all
    depends_on:
      - rest-api-author
      - rest-api-book

  rest-api-author:
    build: ./REST/services/Author
    container_name: rest-api-author
    command: "node index.js"
    ports:
      - "3000:3000"
    networks:
      - all
    depends_on:
      - rest-api-author-db

  rest-api-book:
    build: ./REST/services/Book
    container_name: rest-api-book
    command: "node index.js"
    ports:
      - "3001:3001"
    networks:
      - all
    depends_on:
      - rest-api-book-db

  #### REST DB ####
  rest-api-author-db:
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=1200"
      - "-c"
      - "idle_session_timeout=10000"
      - "-c"
      - "idle_in_transaction_session_timeout=10000"
    environment:
      POSTGRES_DB: author_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - graphql-rest-author-db-data:/var/lib/postgresql/data
      - "./REST/services/Author/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - all

  rest-api-book-db:
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=1200"
      - "-c"
      - "idle_session_timeout=10000"
      - "-c"
      - "idle_in_transaction_session_timeout=10000"
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
    volumes:
      - graphql-rest-book-db-data:/var/lib/postgresql/data
      - "./REST/services/Book/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - all

volumes:
  graphql-rest-author-db-data:
    driver: local
  graphql-rest-book-db-data:
    driver: local
