version: "3.8"

networks:
  microservices:
  author-net:
  book-net:

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
      - "9876:9876"
      - "8443:8443"
    environment:
      - LOG_LEVEL=debug
    networks:
      - microservices
    depends_on:
      - api-author
      - api-book

  api-author:
    build: ./services/Author
    container_name: api-author
    command: "node index.js"
    ports:
      - "3000:3000"
    networks:
      - microservices
      - author-net
    depends_on:
      - api-author-db

  api-book:
    build: ./services/Book
    container_name: api-book
    command: "node index.js"
    ports:
      - "3001:3001"
    networks:
      - microservices
      - book-net
    depends_on:
      - api-book-db

  api-author-db:
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=1200"
      - "-c"
      - "idle_session_timeout=10000"
      - "-c"
      - "idle_in_transaction_session_timeout=10000"
    environment:
      POSTGRES_DB: author_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - rest-author-db-data:/var/lib/postgresql/data
      - "./services/Author/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - author-net

  api-book-db:
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=1200"
      - "-c"
      - "idle_session_timeout=10000"
      - "-c"
      - "idle_in_transaction_session_timeout=10000"
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
    volumes:
      - rest-book-db-data:/var/lib/postgresql/data
      - "./services/Book/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - book-net

volumes:
  rest-author-db-data:
    driver: local
  rest-book-db-data:
    driver: local
