version: "3.8"

networks:
  microservices:
  author-net:

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
      - "9876:9876"
      - "8443:8443"
    environment:
      - LOG_LEVEL=debug
    networks:
      - microservices

  api-author:
    build: ./services/Author
    container_name: api-author
    command: "node index.js"
    ports:
      - "3000:3000"
    networks:
      - microservices
      - author-net
    depends_on:
      - api-author-db

  api-author-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: author_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - './services/Author/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - author-net

volumes:
  db-data:
    driver: local
